/**
 * 세금 카테고리 상수 정의
 * ATO 표준 카테고리 코드 및 표시명 매핑
 */

export const TAX_CATEGORIES = {
  // Income Categories
  INCOME_SALES_CLEANING: 'Trading Revenue',
  INCOME_REFUND_REIMBURSEMENT: 'Refund/Reimbursement',
  INCOME_OTHER_BUSINESS: 'Other Business Income',
  NON_TAXABLE_CASH_DEPOSIT: 'Non-Taxable Cash Deposit',
  
  // Equity Categories
  EQUITY_SHARE_CAPITAL: 'Share Capital',
  
  // Expense Categories
  EXPENSE_STARTUP_INCORPORATION: 'Startup Costs',
  EXPENSE_FUEL_TRAVEL: 'Fuel',
  EXPENSE_MOTOR_VEHICLE: 'Vehicle Maintenance',
  EXPENSE_TRAVEL_TRANSPORT: 'Travel - Transport',
  EXPENSE_TRAVEL_ACCOMMODATION: 'Travel - Accommodation',
  EXPENSE_TRAVEL_MEALS: 'Travel - Meals',
  EXPENSE_TRAVEL_PARKING_TOLLS: 'Travel - Parking/Tolls',
  EXPENSE_MEALS_ENTERTAINMENT: 'Meals & Entertainment',
  EXPENSE_INSURANCE_PROFESSIONAL: 'Insurance/Professional',
  EXPENSE_CLEANING_SUPPLIES: 'Cleaning Supplies',
  EXPENSE_UTILITIES_PHONE: 'Utilities/Phone',
  EXPENSE_CLEANING_SUBCONTRACTOR: 'Subcontractor',
  EXPENSE_REPAIRS_MAINTENANCE: 'Repairs & Maintenance',
  EXPENSE_OFFICE_EQUIPMENT: 'Office Equipment & Assets',
  EXPENSE_OFFICE_SUPPLIES: 'Office Supplies',
  EXPENSE_FREIGHT_SHIPPING: 'Freight & Shipping',
  EXPENSE_RENT: 'Rent',
  EXPENSE_MARKETING: 'Marketing & Advertising',
  EXPENSE_WAGES_SALARIES: 'Wages & Salaries',
  EXPENSE_SUPERANNUATION: 'Superannuation',
  EXPENSE_ATO_GST_BAS: 'ATO - GST & BAS',
  EXPENSE_ATO_PAYG_WITHHOLDING: 'ATO - PAYG Withholding',
  EXPENSE_COMPANY_INCOME_TAX: 'Company Income Tax',
  EXPENSE_WORKERS_COMPENSATION: 'Workers Compensation',
  EXPENSE_ACCOUNTING_FEES: 'Accounting & Professional Fees',
  EXPENSE_DIRECTORS_FEES: "Director's Fees",
  EXPENSE_DIRECTOR_LOAN_REPAYMENT: "Director's Loan Repayment",
  
  // Liability Categories
  LIABILITY_DIRECTORS_LOAN: "Director's Loan",
  
  // Transfer Categories
  TRANSFER_INTERNAL: 'Internal Transfer',
  NON_TAXABLE_TRANSFER: 'Non-Taxable Transfer',
  
  // Uncategorized
  UNCATEGORIZED: 'Uncategorized',
} as const

export type TaxCategory = keyof typeof TAX_CATEGORIES

/**
 * 카테고리 그룹별 분류
 */
export const CATEGORY_GROUPS = {
  INCOME: [
    'INCOME_SALES_CLEANING',
    'INCOME_REFUND_REIMBURSEMENT',
    'INCOME_OTHER_BUSINESS',
    'NON_TAXABLE_CASH_DEPOSIT',
  ],
  EXPENSES: [
    'EXPENSE_STARTUP_INCORPORATION',
    'EXPENSE_FUEL_TRAVEL',
    'EXPENSE_MOTOR_VEHICLE',
    'EXPENSE_TRAVEL_TRANSPORT',
    'EXPENSE_TRAVEL_ACCOMMODATION',
    'EXPENSE_TRAVEL_MEALS',
    'EXPENSE_TRAVEL_PARKING_TOLLS',
    'EXPENSE_MEALS_ENTERTAINMENT',
    'EXPENSE_INSURANCE_PROFESSIONAL',
    'EXPENSE_CLEANING_SUPPLIES',
    'EXPENSE_UTILITIES_PHONE',
    'EXPENSE_CLEANING_SUBCONTRACTOR',
    'EXPENSE_REPAIRS_MAINTENANCE',
    'EXPENSE_OFFICE_EQUIPMENT',
    'EXPENSE_OFFICE_SUPPLIES',
    'EXPENSE_FREIGHT_SHIPPING',
    'EXPENSE_RENT',
    'EXPENSE_MARKETING',
    'EXPENSE_WAGES_SALARIES',
    'EXPENSE_SUPERANNUATION',
    'EXPENSE_ATO_GST_BAS',
    'EXPENSE_ATO_PAYG_WITHHOLDING',
    'EXPENSE_COMPANY_INCOME_TAX',
    'EXPENSE_WORKERS_COMPENSATION',
    'EXPENSE_ACCOUNTING_FEES',
    'EXPENSE_DIRECTORS_FEES',
    'EXPENSE_DIRECTOR_LOAN_REPAYMENT',
  ],
  TAX_COMPLIANCE: [
    'EXPENSE_ATO_GST_BAS',
    'EXPENSE_ATO_PAYG_WITHHOLDING',
    'EXPENSE_COMPANY_INCOME_TAX',
  ],
  TRANSFERS_LOANS: [
    'LIABILITY_DIRECTORS_LOAN',
    'TRANSFER_INTERNAL',
    'NON_TAXABLE_TRANSFER',
    'EXPENSE_DIRECTOR_LOAN_REPAYMENT',
  ],
  EQUITY: [
    'EQUITY_SHARE_CAPITAL',
  ],
} as const
