-- Community board: categories, posts, comments for Selpic (same Supabase project as newsletter).
-- Run once in SQL Editor after newsletter tables.

-- ------------------------------------------------------------
-- Categories (slug aligns with storefront category id, e.g. "general")
-- ------------------------------------------------------------
create table if not exists public.community_categories (
  id integer generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  emoji text not null default '💬',
  bg_color text not null default 'bg-blue-100',
  text_color text not null default 'text-blue-800',
  border_color text not null default 'border-blue-300',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  is_default boolean not null default false
);

alter table public.community_categories enable row level security;

-- ------------------------------------------------------------
-- Posts
-- ------------------------------------------------------------
create table if not exists public.community_posts (
  id integer generated by default as identity primary key,
  title text not null,
  content text not null,
  author_display text not null,
  author_user_id text,
  category text not null,
  likes integer not null default 0,
  pinned boolean not null default false,
  hidden boolean not null default false,
  reported boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists community_posts_created_at_idx
  on public.community_posts (created_at desc);
create index if not exists community_posts_category_idx
  on public.community_posts (category);
create index if not exists community_posts_hidden_idx
  on public.community_posts (hidden);

alter table public.community_posts enable row level security;

-- ------------------------------------------------------------
-- Comments
-- ------------------------------------------------------------
create table if not exists public.community_comments (
  id integer generated by default as identity primary key,
  post_id integer not null references public.community_posts (id) on delete cascade,
  author_display text not null,
  author_user_id text,
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists community_comments_post_id_idx
  on public.community_comments (post_id);

alter table public.community_comments enable row level security;

-- APIs use Supabase service role; RLS blocks anon/authenticated direct access.

-- Seed default categories (idempotent).
insert into public.community_categories (slug, name, emoji, bg_color, text_color, border_color, sort_order, is_active, is_default) values
  ('all', 'All', '📋', 'bg-gray-100', 'text-gray-800', 'border-gray-300', 0, true, true),
  ('general', 'General', '💬', 'bg-blue-100', 'text-blue-800', 'border-blue-300', 1, true, true),
  ('design-showcase', 'Design Showcase', '🎨', 'bg-purple-100', 'text-purple-800', 'border-purple-300', 2, true, true),
  ('diy-projects', 'DIY Projects', '🛠️', 'bg-green-100', 'text-green-800', 'border-green-300', 3, true, true),
  ('tips-tricks', 'Tips & Tricks', '💡', 'bg-orange-100', 'text-orange-800', 'border-orange-300', 4, true, true),
  ('questions', 'Questions', '❓', 'bg-red-100', 'text-red-800', 'border-red-300', 5, true, true),
  ('events', 'Events', '📅', 'bg-indigo-100', 'text-indigo-800', 'border-indigo-300', 6, true, true),
  ('off-topic', 'Off-Topic', '🎭', 'bg-gray-100', 'text-gray-800', 'border-gray-300', 7, true, true),
  ('feedback', 'Feedback', '💭', 'bg-teal-100', 'text-teal-800', 'border-teal-300', 8, true, true)
on conflict (slug) do nothing;

-- Quick checks:
-- select slug, name, is_active from public.community_categories order by sort_order;
-- select id, title, category, pinned, hidden from public.community_posts order by created_at desc limit 10;
