  -- Community board: categories, posts, comments for Selpic (same Supabase project as newsletter).
  -- Run once in SQL Editor after newsletter tables.

  -- ------------------------------------------------------------
  -- Categories (slug aligns with storefront nav: all + four post topics)
  -- ------------------------------------------------------------
  create table if not exists public.community_categories (
    id integer generated by default as identity primary key,
    slug text not null unique,
    name text not null,
    emoji text not null default '💬',
    bg_color text not null default 'bg-blue-100',
    text_color text not null default 'text-blue-800',
    border_color text not null default 'border-blue-300',
    sort_order integer not null default 0,
    is_active boolean not null default true,
    is_default boolean not null default false
  );

  alter table public.community_categories enable row level security;

  -- ------------------------------------------------------------
  -- Posts
  -- ------------------------------------------------------------
  create table if not exists public.community_posts (
    id integer generated by default as identity primary key,
    title text not null,
    content text not null,
    author_display text not null,
    author_user_id text,
    category text not null,
    likes integer not null default 0,
    pinned boolean not null default false,
    hidden boolean not null default false,
    reported boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  );

  create index if not exists community_posts_created_at_idx
    on public.community_posts (created_at desc);
  create index if not exists community_posts_category_idx
    on public.community_posts (category);
  create index if not exists community_posts_hidden_idx
    on public.community_posts (hidden);

  alter table public.community_posts enable row level security;

  -- ------------------------------------------------------------
  -- Comments
  -- ------------------------------------------------------------
  create table if not exists public.community_comments (
    id integer generated by default as identity primary key,
    post_id integer not null references public.community_posts (id) on delete cascade,
    author_display text not null,
    author_user_id text,
    content text not null,
    created_at timestamptz not null default now()
  );

  create index if not exists community_comments_post_id_idx
    on public.community_comments (post_id);

  alter table public.community_comments enable row level security;

  -- APIs use Supabase service role; RLS blocks anon/authenticated direct access.

  -- Seed: All + four short topic names (idempotent inserts).
  insert into public.community_categories (slug, name, emoji, bg_color, text_color, border_color, sort_order, is_active, is_default) values
    ('all', 'All', '🌈', 'bg-gray-50', 'text-gray-800', 'border-gray-200', 0, true, true),
    ('daily', 'Daily', '💬', 'bg-sky-50', 'text-sky-800', 'border-sky-200', 1, true, true),
    ('inspired', 'Inspired', '✨', 'bg-amber-50', 'text-amber-900', 'border-amber-200', 2, true, true),
    ('help', 'Help', '🙌', 'bg-emerald-50', 'text-emerald-900', 'border-emerald-200', 3, true, true),
    ('news', 'News', '📅', 'bg-indigo-50', 'text-indigo-900', 'border-indigo-200', 4, true, true)
  on conflict (slug) do nothing;

  -- ------------------------------------------------------------
  -- Optional: migrate an existing DB that still has legacy category rows
  -- ------------------------------------------------------------
  -- Deactivate legacy slugs (keeps historical rows without showing them).
  /*
  update public.community_categories
    set is_active = false
    where slug not in ('all', 'daily', 'inspired', 'help', 'news');
  */

  -- Remap post.category strings to canonical display names (match app mapping).
  /*
  update public.community_posts set category = 'Daily' where category in ('General', 'Off-Topic', 'OffTopic');
  update public.community_posts set category = 'Inspired' where category in ('Design Showcase', 'DIY Projects', 'Tips & Tricks');
  update public.community_posts set category = 'Help' where category in ('Questions', 'Feedback');
  update public.community_posts set category = 'News' where category in ('Events', 'Event');
  */

  -- Quick checks:
  -- select slug, name, is_active from public.community_categories order by sort_order;
  -- select id, title, category, pinned, hidden from public.community_posts order by created_at desc limit 10;
